stages:
  - build
  - docs
  - deploy

# Common variables
variables:
  CCACHE_DIR: _ccache
  COMMON_MESON_FLAGS: "-Dwerror=true -Dglib:werror=false"
  LOADERS_FLAGS: "-Dpng=true -Djpeg=true -Dtiff=true"
  MESON_TEST_TIMEOUT_MULTIPLIER: 3
  FEDORA_IMAGE: "registry.gitlab.gnome.org/gnome/gdk-pixbuf/fedora:v1"

.only-default:
  only:
    - branches
  except:
    - tags

.build-linux:
  before_script:
    - mkdir -p _ccache
  script:
    - meson ${COMMON_MESON_FLAGS} ${LOADERS_FLAGS} ${BUILD_OPTS} _build .
    - ninja -C _build
    - .gitlab/scripts/run-tests.sh _build
  artifacts:
    when: always
    name: "gdk-pixbuf-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
      - "${CI_PROJECT_DIR}/_build/report-${CI_JOB_NAME}.xml"
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/report-${CI_JOB_NAME}.xml"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - _ccache/

style-check-diff:
  extends: .only-default
  image: $FEDORA_IMAGE
  stage: .pre
  allow_failure: true
  script:
    - .gitlab/scripts/run-style-check-diff.sh

meson-fedora-x86_64:
  stage: build
  extends: .build-linux
  image: ${FEDORA_IMAGE}
  needs: []

release-build:
  stage: build
  extends: .build-linux
  image: ${FEDORA_IMAGE}
  needs: []
  variables:
    BUILD_OPTS: "-Dbuildtype=release"

reference:
  stage: docs
  image: ${FEDORA_IMAGE}
  needs: []
  variables:
    BUILD_OPTS: "-Dgtk_doc=true"
  script:
    - meson ${COMMON_MESON_FLAGS} ${LOADERS_FLAGS} ${BUILD_OPTS} _build .
    - ninja -C _build gdk-pixbuf-doc
    - mv _build/docs/html _reference
  artifacts:
    when: on_success
    paths:
      - _reference

pages:
  stage: deploy
  needs: [reference]
  script:
    - mv _reference public
  artifacts:
    paths:
      - public
  only:
    - master

msys2-mingw64:
  stage: build
  needs: []
  tags:
    - win32-ps
  variables:
    MSYSTEM: "MINGW64"
    CHERE_INVOKING: "yes"
  script:
    - C:\msys64\usr\bin\pacman --noconfirm -Syyuu
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab/ci/test-msys2.sh"
  artifacts:
    name: "gdk-pixbuf-${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - _build/meson-logs
