stages:
  - build
  - docs
  - deploy

variables:
  CCACHE_DIR: _ccache

.build-linux:
  image: registry.gitlab.gnome.org/gnome/gdk-pixbuf/master:v2
  stage: build
  before_script:
    - mkdir -p _ccache
  script:
    - meson ${BUILD_OPTS} _build .
    - ninja -C _build
  artifacts:
    when: on_failure
    name: "gdk-pixbuf-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/build_*/meson-logs"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - _ccache/

meson-fedora-x86_64:
  extends: .build-linux
  variables:
    BUILD_OPTS: "-Dpng=true -Djpeg=true -Dtiff=true -Djasper=true"
  after_script:
    - meson test -C _build -t 3

release-build:
  extends: .build-linux
  variables:
    BUILD_OPTS: "-Dpng=true -Djpeg=true -Dtiff=true -Dbuildtype=release"
  after_script:
    - meson test -C _build -t 3

reference:
  extends: .build-linux
  stage: docs
  variables:
    BUILD_OPTS: "-Dgtk_doc=true"
  after_script:
    - ninja -C _build gdk-pixbuf-doc
    - mv _build/docs/html _reference
  artifacts:
    when: on_success
    paths:
      - _reference

pages:
  stage: deploy
  script:
    - mv _reference public
  artifacts:
    paths:
      - public
  only:
    - master

msys2-mingw64:
  stage: build
  tags:
    - win32-ps
  variables:
    MSYSTEM: "MINGW64"
    CHERE_INVOKING: "yes"
  script:
    - C:\msys64\usr\bin\pacman --noconfirm -Syyuu
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab/ci/test-msys2.sh"
  artifacts:
    name: "gdk-pixbuf-${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - _build/meson-logs
